// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// deviance_simplex
arma::vec deviance_simplex(const arma::vec& y, const arma::vec& mu);
RcppExport SEXP _simplexgof_deviance_simplex(SEXP ySEXP, SEXP muSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    rcpp_result_gen = Rcpp::wrap(deviance_simplex(y, mu));
    return rcpp_result_gen;
END_RCPP
}
// u1_vec
arma::vec u1_vec(const arma::vec& y, const arma::vec& mu, const arma::vec& fd);
RcppExport SEXP _simplexgof_u1_vec(SEXP ySEXP, SEXP muSEXP, SEXP fdSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type fd(fdSEXP);
    rcpp_result_gen = Rcpp::wrap(u1_vec(y, mu, fd));
    return rcpp_result_gen;
END_RCPP
}
// build_delta
arma::mat build_delta(const arma::mat& mX, const arma::mat& mZ, const arma::vec& Tdiag, const arma::vec& Sigma, const arma::vec& Hdiag, const arma::vec& u1, const arma::vec& u2, const arma::vec& ydiff);
RcppExport SEXP _simplexgof_build_delta(SEXP mXSEXP, SEXP mZSEXP, SEXP TdiagSEXP, SEXP SigmaSEXP, SEXP HdiagSEXP, SEXP u1SEXP, SEXP u2SEXP, SEXP ydiffSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mZ(mZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tdiag(TdiagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Hdiag(HdiagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u1(u1SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type u2(u2SEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type ydiff(ydiffSEXP);
    rcpp_result_gen = Rcpp::wrap(build_delta(mX, mZ, Tdiag, Sigma, Hdiag, u1, u2, ydiff));
    return rcpp_result_gen;
END_RCPP
}
// compute_kvec
arma::vec compute_kvec(const arma::mat& Delta, const arma::mat& A_inv, const arma::mat& B_star, const arma::mat& A_star, const arma::vec& J_vec, const arma::mat& mX, const arma::mat& mZ, const arma::vec& Sigma, const arma::vec& Tdiag, const arma::vec& Hdiag, const arma::vec& q_vec, const arma::vec& f_star, const arma::vec& d_star);
RcppExport SEXP _simplexgof_compute_kvec(SEXP DeltaSEXP, SEXP A_invSEXP, SEXP B_starSEXP, SEXP A_starSEXP, SEXP J_vecSEXP, SEXP mXSEXP, SEXP mZSEXP, SEXP SigmaSEXP, SEXP TdiagSEXP, SEXP HdiagSEXP, SEXP q_vecSEXP, SEXP f_starSEXP, SEXP d_starSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type Delta(DeltaSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A_inv(A_invSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type B_star(B_starSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type A_star(A_starSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type J_vec(J_vecSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mZ(mZSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Sigma(SigmaSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Tdiag(TdiagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type Hdiag(HdiagSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type q_vec(q_vecSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type f_star(f_starSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type d_star(d_starSEXP);
    rcpp_result_gen = Rcpp::wrap(compute_kvec(Delta, A_inv, B_star, A_star, J_vec, mX, mZ, Sigma, Tdiag, Hdiag, q_vec, f_star, d_star));
    return rcpp_result_gen;
END_RCPP
}
// rinvgauss_cpp
arma::vec rinvgauss_cpp(int n, double mu, double lambda);
RcppExport SEXP _simplexgof_rinvgauss_cpp(SEXP nSEXP, SEXP muSEXP, SEXP lambdaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    rcpp_result_gen = Rcpp::wrap(rinvgauss_cpp(n, mu, lambda));
    return rcpp_result_gen;
END_RCPP
}
// rsimplex_cpp
arma::vec rsimplex_cpp(const arma::vec& mu, const arma::vec& sig2);
RcppExport SEXP _simplexgof_rsimplex_cpp(SEXP muSEXP, SEXP sig2SEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type mu(muSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type sig2(sig2SEXP);
    rcpp_result_gen = Rcpp::wrap(rsimplex_cpp(mu, sig2));
    return rcpp_result_gen;
END_RCPP
}
// loglik_simplex_cpp
double loglik_simplex_cpp(const arma::vec& vP, const arma::vec& y, const arma::mat& mX, const arma::mat& mZ);
RcppExport SEXP _simplexgof_loglik_simplex_cpp(SEXP vPSEXP, SEXP ySEXP, SEXP mXSEXP, SEXP mZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vP(vPSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mZ(mZSEXP);
    rcpp_result_gen = Rcpp::wrap(loglik_simplex_cpp(vP, y, mX, mZ));
    return rcpp_result_gen;
END_RCPP
}
// score_simplex_cpp
arma::vec score_simplex_cpp(const arma::vec& vP, const arma::vec& y, const arma::mat& mX, const arma::mat& mZ);
RcppExport SEXP _simplexgof_score_simplex_cpp(SEXP vPSEXP, SEXP ySEXP, SEXP mXSEXP, SEXP mZSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type vP(vPSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mX(mXSEXP);
    Rcpp::traits::input_parameter< const arma::mat& >::type mZ(mZSEXP);
    rcpp_result_gen = Rcpp::wrap(score_simplex_cpp(vP, y, mX, mZ));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_simplexgof_deviance_simplex", (DL_FUNC) &_simplexgof_deviance_simplex, 2},
    {"_simplexgof_u1_vec", (DL_FUNC) &_simplexgof_u1_vec, 3},
    {"_simplexgof_build_delta", (DL_FUNC) &_simplexgof_build_delta, 8},
    {"_simplexgof_compute_kvec", (DL_FUNC) &_simplexgof_compute_kvec, 13},
    {"_simplexgof_rinvgauss_cpp", (DL_FUNC) &_simplexgof_rinvgauss_cpp, 3},
    {"_simplexgof_rsimplex_cpp", (DL_FUNC) &_simplexgof_rsimplex_cpp, 2},
    {"_simplexgof_loglik_simplex_cpp", (DL_FUNC) &_simplexgof_loglik_simplex_cpp, 4},
    {"_simplexgof_score_simplex_cpp", (DL_FUNC) &_simplexgof_score_simplex_cpp, 4},
    {NULL, NULL, 0}
};

RcppExport void R_init_simplexgof(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
