# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

deviance_simplex <- function(y, mu) {
    .Call(`_simplexgof_deviance_simplex`, y, mu)
}

u1_vec <- function(y, mu, fd) {
    .Call(`_simplexgof_u1_vec`, y, mu, fd)
}

build_delta <- function(mX, mZ, Tdiag, Sigma, Hdiag, u1, u2, ydiff) {
    .Call(`_simplexgof_build_delta`, mX, mZ, Tdiag, Sigma, Hdiag, u1, u2, ydiff)
}

compute_kvec <- function(Delta, A_inv, B_star, A_star, J_vec, mX, mZ, Sigma, Tdiag, Hdiag, q_vec, f_star, d_star) {
    .Call(`_simplexgof_compute_kvec`, Delta, A_inv, B_star, A_star, J_vec, mX, mZ, Sigma, Tdiag, Hdiag, q_vec, f_star, d_star)
}

rinvgauss_cpp <- function(n, mu, lambda) {
    .Call(`_simplexgof_rinvgauss_cpp`, n, mu, lambda)
}

rsimplex_cpp <- function(mu, sig2) {
    .Call(`_simplexgof_rsimplex_cpp`, mu, sig2)
}

loglik_simplex_cpp <- function(vP, y, mX, mZ) {
    .Call(`_simplexgof_loglik_simplex_cpp`, vP, y, mX, mZ)
}

score_simplex_cpp <- function(vP, y, mX, mZ) {
    .Call(`_simplexgof_score_simplex_cpp`, vP, y, mX, mZ)
}

